# Site settings
title: Signal Chaos 
email:
description: > # this means to ignore newlines until "baseurl:"
  Observations in application security
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://s1gnalcha0s.github.io" # the base hostname & protocol for your site
twitter_username: s1gnalcha0s

# Build settings
markdown: kramdown
